### ISSUE TITLE
Organizar las carpetas en el repo

### ISSUE THREAD

**Issue by nicolasdsanchez** [ETERNETDEV/Imagen#1]
Hola chicos @dariogue @PabloIrigoin, vamos a organizar las imágenes. La idea es ponerlas en carpetas y sub carpetas con nombres claros para saber que es cada cosa. Además de crear un archivo readme para cada carpeta con la información de que se trata la carpeta y a donde apunta, también que es cada imagen y que tamaño debe tener o tiene actualmente.
Por lo que vi las dos carpetas que hay ahora son la info al pie de los mails (infomail) y la carpeta firma tiene que ver con eso tambien? se podrán agrupar?
Con el archivo readme les doy una mano si quieren...
Voy a ir subiendo las imagenes del/los banner de la web de eternet y apuntándolos a este repo, esto también va a servir para la web nueva.

**Comment by nicolasdsanchez** [comment]
@dariogue @PabloIrigoin Ahí subí las imágenes del banner de la pagina principal de la web de eternet con su respectivo archivo readme.md

**Comment by PabloIrigoin** [comment]
Hola @nicolasdsanchez según entiendo las imágenes siempre van a tener ese nombre. Es decir para cambiar el orden debería renombrarlas a todas respetando la secuencia. No se podría poner directamente 1.jpg 2.jpg... etc. 

Una consulta: si cambiamos una imagen esta se va a  tener que seguir teniendo el mismo nombre, en tal caso es probable que no se actualice el navegador de cliente y por tanto vea siempre la misma hasta que se actualice el cache del navegador. Esto es así o no?

**Comment by nicolasdsanchez** [comment]
> Hola @nicolasdsanchez según entiendo las imágenes siempre van a tener ese nombre. Es decir para cambiar el orden debería renombrarlas a todas respetando la secuencia. No se podría poner directamente 1.jpg 2.jpg... etc.

Por ahora no están apuntadas todavía a la Web. En breve lo voy a hacer. La idea es como vos decís Pablo van a tener ese nombre y se puede cambiar a 1.jpg 2.jpg, etc No quise hacerlo todavía porque no están apuntadas.

> Una consulta: si cambiamos una imagen esta se va a tener que seguir teniendo el mismo nombre, en tal caso es probable que no se actualice el navegador de cliente y por tanto vea siempre la misma hasta que se actualice el cache del navegador. Esto es así o no?

Para esto había implementado una solución que es agregarle un id (?numero_random) a la imagen cuando se escribe el archivo xml que contiene las imágenes de banner, esto hace que detecte que la imagen cambio y no la levante del cache. Queda algo por el estilo: `<img src="1.jpg?1287361287" alt="">`
El tema es que el archivo xml no se escribe siempre que se entra a la web, así que puede ocurrir lo que decis... voy a ver como lo soluciono.

cc @PabloIrigoin
