### ISSUE TITLE
Imagen para email de autenticación no es genérica

### ISSUE THREAD

**Issue by Germandf** [ETERNETDEV/Imagen#2]
Hola Dario, te molesto por esta imagen que te pedí para el mail de autenticación. Este correo se usa tanto para darse de alta (registro) como para recuperar la cuenta, por lo que el título que tiene actualmente no me sirve para ambos casos, sólo para el último.

Ruta: mailing/recupero-cuenta/recupero-cuenta.jpg

![recupero-cuenta](https://user-images.githubusercontent.com/69018178/178317197-53256423-5ed9-4344-ba61-533243ab243c.jpg)

Te parece modificarlo a algo así?

```
Identificación

Datos necesarios para autenticarte
```

Sino, en vez de `Identificación` podría ser `Autenticación` u otra similar. 

El subtítulo podría ser también `Datos necesarios para autenticar/confirmar tu identidad` o quizás quedarse como está. 

Todo eso lo dejo a tu criterio. Lo que necesito es que me sirva para cualquier caso relacionado a autenticación, así no hacemos una imagen para cada caso actual y futuro.

**Comment by dariogue** [comment]
Hola @Germandf: Para que sea genérico como indicas y te sirva para ambos cambiaría el TAG por Autenticación y como titulo lo dejaría como está. Tiré la otra y deje esta (autenticacion.jpg).

Te parece?

![autenticacion](https://user-images.githubusercontent.com/68999547/178327480-5fda15e0-c48b-4047-a577-1a844b9c69b0.jpg)

**Comment by Germandf** [comment]
Me gusta autenticación en el título, pero no me termine de convencer "activación" en el subtítulo, no se si necesariamente se está activando algo.

Te parece `Datos necesarios para continuar`? Se entiende que esto es parte de un proceso, el proceso de autenticación y que el usuario quiere continuar a través del mismo.

**Comment by dariogue** [comment]
Si estos de acuerdo en "para continuar"

**Comment by Germandf** [comment]
Buenisimo! ahora en un rato actualizo la ruta para cambiar el nombre de la carpeta, gracias!
